questions =  [
    //World War II. Total weight: 6 points.
    {"id": 0, "question": "In 1937, Japan (Side A) invaded the Republic of China (Side B).", "effects": {"aggression": 1, "genocide": 1}}, //Japanese occupation of Japan, genocidal. "Republic of China" largely a dictatorship at this point in time.
    {"id": 1, "question": "From 1938-1940, Germany, with the support of Italy, Hungary, Bulgaria, and Romania (Side A), invaded Austria, Czechoslovakia, Poland, Belgium, the Netherlands, Luxembourg, Denmark, Norway, France, Greece, Albania, and Yugoslavia (Side B).", "effects": {"aggression": 2, "genocide": 2, "democracy": -2}}, // This question could be divided into several separate phases, but the answers should generally align anyway.
    {"id": 2, "question": "From 1939-1940, the Soviet Union (Side A) invaded Poland, Finland, and the Baltic states (Side B).", "effects": {"aggression": 1, "genocide": 1, "democracy": -1 }}, //Soviet Union largely genocidal at this point; Baltics, not so genocidal.
    {"id": 3, "question": "In 1941, Germany (Side A) invaded the Soviet Union (Side B).", "effects": {"aggression": 1 }}, //Some dispute over which was less democratic or more genocidal, but both were terrible.
    {"id": 4, "question": "In 1940 and 1941, Japan (Side A) invaded or attacked various Pacific territories belonging to the French, Dutch, British, and Americans (Side B).", "effects": {"aggression": 1, "genocide": 1, "democracy": -1}}, //Japanese occupation of everywhere else ... ALSO genocidal, but in this case they're also fighting against democracy.  

    //After World War II but concluded. Democracy-aggression linkage totals 4 points in this section.
    {"id": 10, "question": "In 1948, the Jewish-governed areas of the British Mandate of Palestine (Side A) declared their independence from Britain as the state of Isreal, which was immediately invaded by the Arab League (Side B) with the intention of erasing the new country.", "effects": {"aggression": -1, "genocide": -1, "democracy": 1 }},
    {"id": 11, "question": "In 1950, North Korea (Side A) invaded South Korea (Side B).", "effects": {"aggression": 1 }},
    {"id": 12, "question": "In 1950, China (Side A) invaded and annexed Tibet (Side B).", "effects": {"aggression": 1 }},
    {"id": 13, "question": "In 1953, the democratically-elected prime minister of Iran (Side A) was overthrown in a monarchist coup backed by the US and UK (Side B).", "effects": {"democracy": 1 }},
    {"id": 14, "question": "In 1956, Israel, Britain, and France (Side A) invaded Egypt (Side B) in response to Egyptian trade blockages in the Suez Canal Crisis.", "effects": {"aggression": 1, "democracy": 1 }}, //Democracy aggression!
    {"id": 15, "question": "In 1958, China (Side A) attempted to land troops on islands controlled by Taiwan (Side B).", "effects": {"aggression": 1 }},
    {"id": 16, "question": "In 1962 and again in 1965, China (Side A) invaded and annexed lands formerly belonging to India (Side B).", "effects": {"aggression": 1, "democracy":- 1 }},
    {"id": 17, "question": "In 1965, Pakistan (Side A) invaded territory controlled by India (Side B) across a border established in 1948.", "effects": {"aggression": 1, "democracy":- 1 }},
    {"id": 19, "question": "In 1967, Israel (Side A) made pre-emptive strikes against the Arab League (Side B) in anticipation of an invasion.", "effects": {"aggression": 1, "democracy": 1 }}, //Democracy aggression!
    {"id": 20, "question": "In 1967, China (Side A) launched an attack on Indian soldiers (Side B) and was defeated, pushing the border back.", "effects": {"aggression": 1, "democracy":- 1 }},
    {"id": 21, "question": "In 1969, China (Side A) attacked the Soviet Union (Side B) over possession of several river islands.", "effects": {"aggression": 1 }},
    {"id": 23, "question": "In 1971, India (Side A) attacked Pakistan (Side B) in reaction to Pakistan's crackdown on Bengal separatists and genocide of Bengal Hindus, creating the independent state of Bangladesh.", "effects": {"aggression": 1, "democracy": 1, "genocide": -1 }}, //Democracy aggression! Bengladesh mostly Muslim, but religious persecution of Hindu Bengals a key motive for Indian intervention.
    {"id": 24, "question": "In 1973, the Arab League (Side A) launched a surprise attack against Israel (Side B), beginning the Yom Kippur War.", "effects": {"aggression": 1, "democracy": -1 }},
    {"id": 25, "question": "In 1975, Indonesia (Side A) invaded and annexed East Timor (Side B) following Portuguese withdrawal from East Timor and its other colonies, citing postcolonial reunification. East Timor remained occupied until 1999.", "effects": {"aggression": 1, "genocide": 1 }}, //A third of the population of East Timor died from this.
    {"id": 26, "question": "In 1977, Kampuchea [Cambodia] (Side A) launched a series of attacks on Vietnamese villages. Vietnam (Side B) responded by invading and deposing the Khmer Rouge government. China (also Side A) responded in 1979 by launching a surprise attack on Vietnam.", "effects": {"aggression": 1,"genocide": 1}}, 
    {"id": 28, "question": "In 1980, Iraq (Side A) invaded Iran (Side B).", "effects": {"democracy": -1, "genocide": 1, "aggression": 1}}, //Iran had elections to a greater degree than Iraq at this point in time. Saddam's genocidal efforts against Kurds during the late phase of this conflict.
    {"id": 29, "question": "In 1988, Armenians (Side A) in Armenian-majority areas voted to secede from the Soviet Socialist Republic of Azerbaijan (Side B). Azeri forces responded violently, beginning a six-year war in which they lost significant territory.", "effects": {"democracy": 1, "aggression": -1,  }},  //Ethnic cleansing and violence on both sides (even if the Azeris very clearly initiated both the informal violence and the formal violence).
    {"id": 30, "question": "In 1991, Iraq (Side A) invaded Kuwait, which was then liberated by a 42-nation coalition (Side B).", "effects": {"aggression": 1}}, //Kuwait not democratic.
    {"id": 31, "question": "In 2003, Iraq (Side A) was invaded by the United States (Side B) amid allegations of danger from weapons of mass destruction being sent to terrorists.", "effects": {"aggression": -1, "democracy": -1 }}, //Democratic aggression case. It is unambiguous that Iraq is now a much more democratic state as a result of this invasion.
    {"id": 32, "question": "In 2008, Russian, South Ossetian, and later Abkhaz troops (Side A) attacked and invaded Georgia (Side B), which responded by invading South Ossetia.", "effects": {"democracy": -1, "aggression": 1}}, 
    {"id": 33, "question": "In 2014, Russia (Side A) carried out a limited invasion of Ukraine (Side B), annexing Crimea and setting up unrecognized breakaway republics on Ukraine's eastern border.", "effects": {"democracy": -1, "aggression": 1}}, //Genocidal activity in this phase not well-documented; also, many people held a different opinion of this than the subsequent 2022 full-scale invasion.


    //Present conflicts
    {"id": 40, "question": "In 1955, a civil war began in Sudan between the governing military dictatorship of northern Sudan (Side A) and rebels in southern Sudan (Side B). The conflict has continued on and off to the present day, leading eventually to the widespread recognition of the independence of South Sudan.", "effects": { "genocide": 1}},
    {"id": 41, "question": "From 1980 to the present, Uighurs (Side A) have been engaged in an on-and-off rebellion against the People's Republic of China (Side B).", "effects": {"genocide": -1,  }}, //Genocide in this case being primarily documented in terms of cultural destruction and forced sterilization rather than death camps.
    {"id": 41, "question": "In 2009, the Nigerian military (Side A) forcibly suppressed the Boko Haram movement (Side B), which responded with a violent rebellion, terrorist attacks, and mass kidnappings.", "effects": {"genocide": -1, "democracy": -1, "aggression": 1  }}, //Rare case of genocidal maniacs not actually being the ones to start the war, though they escalated it enormously.
    {"id": 42, "question": "In 2020 and then again in 2024, Armenia (Side A) was invaded by Azerbaijan (Side B) seeking to regain territory lost in the previous war and remove Armenians from disputed territories.", "effects": {"democracy": 1, "aggression": -1,   "genocide": -1}}, //Azerbaijan now openly genocidal dictatorship 
    {"id": 43, "question": "In 2022, Russia (Side A) carried out a large-scale invasion of Ukraine (Side B).", "effects": {"democracy": -1, "aggression": 1, "genocide": 1}}, //Genocidal activity well-documented
    {"id": 44, "question": "In 2023, Hamas (Side A) launched a large pogrom across the Gazan border on Israel (Side B), which responded by invading the Gaza Strip to eliminate Hamas.", "effects": {"democracy": -1, "aggression": 1 }}, //Proven genocidal intentions and activity by Hamas; unproven allegations of genocide on a larger scale by Israel with intent not clearly established; ergo, not scored on genocide.
    
    //Hypothetical conflicts - these are scored primarily on unambiguous V-Dem differences. As these are not scored on aggression, this creates opportunities to enter into the rarer two quadrants, though few people will get there without trying very hard.
    {"id": 50, "question": "Suppose that there is a future conflict between China (Side A) and Taiwan (Side B). Which do you think you will more likely support?", "effects": {"democracy": -1 }},
    {"id": 51, "question": "Suppose that there is a future conflict between China (side A) and Philippines (side B). Which do you think you will more likely support?", "effects": {"democracy": -1,}},
    {"id": 52, "question": "Suppose that there is a future conflict between China (side A) and India (side B). Which do you think you will more likely support?", "effects": {"democracy": -1 }},
    {"id": 53, "question": "Suppose that there is a future conflict between China (side A) and Indonesia (side B). Which do you think you will more likely support?", "effects": {"democracy": -1,  }},
    {"id": 54, "question": "Suppose that there is a future conflict between Pakistan (side A) and India (side B). Which do you think you will more likely support?", "effects": {"democracy": -1 }},
    {"id": 55, "question": "Suppose that there is a future conflict between Pakistan (side A) and Iran (side B). Which do you think you will more likely support?", "effects": {"democracy": 1}},
    {"id": 56, "question": "Suppose that there is a future conflict between Greece (side A) and Turkey (side B). Which do you think you will more likely support?", "effects": {"democracy": 1 }},
    {"id": 57, "question": "Suppose that there is a future conflict between Guyana (side A) and Venezuela (side B). Which do you think you will more likely support?", "effects": {"democracy": 1 }},
    {"id": 58, "question": "Suppose that there is a future conflict between Brazil (side A) and Venezuela (side B). Which do you think you will more likely support?", "effects": {"democracy": 1 }},
    {"id": 59, "question": "Suppose that there is a future conflict between Azerbaijan (side A) and Armenia (side B). Which do you think you will more likely support?", "effects": {"democracy": -1, "genocide": 1 }}, //Current Azeri government very openly genocidal in intentions.
    {"id": 60, "question": "Suppose that there is a future conflict between the Baltic states (side A) and Russia (side B). Which do you think you will more likely support?", "effects": {"democracy": 1}},
    {"id": 61, "question": "Suppose that there is a future conflict between the Khazakhstan (side A) and Russia (side B). Which do you think you will more likely support?", "effects": {"democracy": 1 }},
    {"id": 62, "question": "Suppose that there is a future conflict between the Khazakhstan (side A) and China (side B). Which do you think you will more likely support?", "effects": {"democracy": 1,  }},
    {"id": 63, "question": "Suppose that there is a future conflict between Israel (side A) and some number of surrounding Arab states (side B). Which do you think you will more likely support?", "effects": {"democracy": 1 }}
];
