questions =  [
    {"id": 0, "question": "Wage labour under capitalism is an inherently exploitative system.", "effects": {"right": -1}},
    {"id": 1, "question": "An individual can’t claim any rights against the state, as it is the state that gives them those rights in the first place.", "effects": {"auth": 1}},
    {"id": 2, "question": "A hunter-gatherer, subsistence farming, or nomadic lifestyle where we live off the land is preferable compared with our sedentary civilisations. I could say a life off the grid is somewhat appealing to me.", "effects": {"prog": -1}},
    {"id": 3, "question": "A more defining difference between people is in their social class than their nationality.", "effects": {"right": -1}},
    {"id": 4, "question": "Possession of drugs for personal use shouldn’t be a criminal offence.", "effects": {"auth": -1}},
    {"id": 5, "question": "Modern civilisation is a violation of our natural state of nature. That’s why we’re so miserable. Humans aren’t adapted to live like how we do today.", "effects": {"prog": -1}},
    {"id": 6, "question": "Wealth redistribution punishes success and rewards laziness.", "effects": {"right": 1}},
    {"id": 7, "question": "It is morally unacceptable for a child to keep secrets from their parents.", "effects": {"auth": 1}},
    {"id": 8, "question": "Modern technology has improved our lives for the better.", "effects": {"prog": 1}},
    {"id": 9, "question": "It is the responsibility of those with privilege to give a hand to those who are disprivileged in comparison.", "effects": {"right": -1}},
    {"id": 10, "question": "The people should retain the right to overthrow their government if it becomes tyrannical.", "effects": {"auth": -1}},
    {"id": 11, "question": "Even if you think things suck now, let’s be honest, they sucked a lot worse back then.", "effects": {"prog": 1}},
    {"id": 12, "question": "Your failures are your own failures. Stop blaming others and pull yourself up by your bootstraps!", "effects": {"right": 1}},
    {"id": 13, "question": "If we let certain deviant acts or beliefs get out of control, our society is in great danger, it might even possibly collapse. .", "effects": {"auth": 1}},
    {"id": 14, "question": "We should be open minded to new scientific discoveries, and innovations in technologies like artificial intelligence and nanotechnology.", "effects": {"prog": 1}},
    {"id": 15, "question": "When it comes to hierarchy in society, we should by default question its legitimacy, and if it can’t meet its legitimacy, it should be dismantled and replaced by a more egalitarian system.", "effects": {"right": -1}},
    {"id": 16, "question": "Death is a worthy punishment for some heinous crimes like murder and rape.", "effects": {"auth": 1}},
    {"id": 17, "question": "There was a time in history that society was better than it is now.", "effects": {"prog": -1}},
    {"id": 18, "question": "Women are regarded as equal under the law in the Western world, so the societal differences that occur between them are due to their inate biological and psychological differences from men.", "effects": {"right": 1}},
    {"id": 19, "question": "It’s unacceptable that the government spies on its citizens. We have a right to privacy!", "effects": {"auth": -1}},
    {"id": 20, "question": "We should expect and accept that people will be concerned when things change in ways they haven’t changed before.", "effects": {"prog": -1}},
    {"id": 21, "question": "A rising tide lifts all boats. When the wealthy prosper, so do the poor.", "effects": {"right": 1}},
    {"id": 22, "question": "What goes on in a private bedroom between consenting adults is no business of the state.", "effects": {"auth": -1}},
    {"id": 23, "question": "People were happier before we developed our modern ways of life.", "effects": {"prog": -1}},
    {"id": 24, "question": "A society that is classless, moneyless, and stateless is realistically possible.", "effects": {"right": -1}},
    {"id": 25, "question": "The criminal justice system should be based on rehabilitation rather than retribution.", "effects": {"auth": -1}},
    {"id": 26, "question": "Transcending the barriers of our human bodies through cybernetics and brain implants is something I believe could bring positives to the world.", "effects": {"prog": 1}},
    {"id": 27, "question": "If the market isn’t free, then the people aren’t free either.", "effects": {"right": 1}},
    {"id": 28, "question": "Of course to be safe you have to give up some of your so-called “freedoms”. That’s acceptable if it protects you from criminals and terrorists.", "effects": {"auth": 1}},
    {"id": 29, "question": "Humanity should push the boundaries of what’s possible and stretch for new frontiers. Reach for the stars!", "effects": {"prog": 1}},
    {"id": 30, "question": "Everyone should be equal. I know it’s a cliché, but I truly believe it.", "effects": {"right": -1}},
    {"id": 31, "question": "Abortion should in most cases be illegal. I would only make a few exceptions, if any at all.", "effects": {"auth": 1}},
    {"id": 32, "question": "Long ago, things were simpler, and perhaps we should return to those times.", "effects": {"prog": -1}},
    {"id": 33, "question": "Prosperity comes to our society when we nurture the gifts of the gifted. They should be prioritised in our education system.", "effects": {"right": 1}},
    {"id": 34, "question": "People should have the rights to own firearms, if that’s what they want to do.", "effects": {"auth": -1}},
    {"id": 35, "question": "Modern science makes our lives better. Just look at our life expectancy. The truth is self-evident.", "effects": {"prog": 1}},
    {"id": 36, "question": "We should make the struggle for LGBTQ+ rights, feminism, minority rights, etc. a focus of our activism.", "effects": {"right": -1}},
    {"id": 37, "question": "Pornography, depicting consenting adults should be legal for the adult population.", "effects": {"auth": -1}},
    {"id": 38, "question": "This might be a hot take, but I really think we should be reducing the size of our economy.", "effects": {"prog": -1}},
    {"id": 39, "question": "There is no society, there are only individuals.", "effects": {"right": 1}},
    {"id": 40, "question": "Our schools could really learn some good lessons from how the military works.", "effects": {"auth": 1}},
    {"id": 41, "question": "I look to the future with optimism. Whatever we come against, I trust humanity to prevail. We’ve always found a way.", "effects": {"prog": 1}},
    {"id": 42, "question": "Necessities to live like food, water, shelter, etc. should not be commodities to be bought and sold.", "effects": {"right": -1}},
    {"id": 43, "question": "It’s more important our children learn respect for their elders than anything else.", "effects": {"auth": 1}},
    {"id": 44, "question": "The Enlightenment was one of, if not the most important, influential, and beneficial moments of humanity’s history.", "effects": {"prog": 1}},
    {"id": 45, "question": "Some people are just better and therefore more deserving than others; it’s as simple as that.", "effects": {"right": 1}},
    {"id": 46, "question": "The state shouldn’t enforce a preference for either one religion over another, or a preference for the absence of religion.", "effects": {"auth": -1}},
    {"id": 47, "question": "The industrial revolution and its consequences have been a disaster for the human race.", "effects": {"prog": -1}},
];
